version: '3'

services:
  web:
    build: .
    container_name: ${WEB_CONTAINER}
    ports:
      - '${WEB_HOST_PORT}:${WEB_CONTAINER_PORT}'
    depends_on:
      - db
    restart: on-failure
    environment:
      - DEBUG=true
  
  db:
    image: mariadb:latest
    container_name: ${DB_CONTAINER}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_SPECIAL_USER}
      MYSQL_PASSWORD: ${DB_SPECIAL_PASSWORD}
      DEBUG: 'true'
    ports:
      - '${DB_HOST_PORT}:${DB_CONTAINER_PORT}'
    volumes:
      - '${DB_HOST_VOLUME}:${DB_CONTAINER_VOLUME}'
  
  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER}
    ports:
      - '${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}'
    volumes:
      - '${NGINX_HOST_VOLUME}:${NGINX_CONTAINER_VOLUME}'
    depends_on:
      - web

  mqtt:
      image: eclipse-mosquitto:latest
      container_name: ${MQTT_CONTAINER}
      ports:
        - '${MQTT_HOST_PORT}:${MQTT_CONTAINER_PORT}' #default mqtt port
        - '${MQTT_WS_HOST_PORT}:${MQTT_WS_CONTAINER_PORT}' #default mqtt port for websockets
      volumes:
        - '${MQTT_HOST_CONF_VOLUME}:${MQTT_CONTAINER_CONF_VOLUME}'
        - '${MQTT_HOST_DATA_VOLUME}:${MQTT_CONTAINER_DATA_VOLUME}'
        - '${MQTT_HOST_LOG_VOLUME}:${MQTT_CONTAINER_LOG_VOLUME}'
        - '${MQTT_HOST_PWFILE_VOLUME}:${MQTT_CONTAINER_PWFILE_VOLUME}'

